// A practical list of major Israeli cities/towns for the registration form's
// city dropdown — not the full official ~1200-settlement registry. "אחר"
// (other) is handled by the form as a free-text fallback, same pattern as
// DANCE_STYLES in lib/pricing.ts. Adjust with Dani if this list is missing
// somewhere her studio managers commonly come from.
export const ISRAELI_CITIES = [
  "ירושלים",
  "תל אביב-יפו",
  "חיפה",
  "ראשון לציון",
  "פתח תקווה",
  "אשדוד",
  "נתניה",
  "באר שבע",
  "בני ברק",
  "חולון",
  "רמת גן",
  "אשקלון",
  "רחובות",
  "בת ים",
  "בית שמש",
  "כפר סבא",
  "הרצליה",
  "חדרה",
  "מודיעין-מכבים-רעות",
  "נצרת",
  "לוד",
  "רמלה",
  "רעננה",
  "רהט",
  "הוד השרון",
  "גבעתיים",
  "קריית אתא",
  "נהריה",
  "אילת",
  "קריית גת",
  "עפולה",
  "רמת השרון",
  "כפר יונה",
  "טבריה",
  "נס ציונה",
  "קריית מוצקין",
  "יבנה",
  "טירת כרמל",
  "עכו",
  "אלעד",
  "קריית ביאליק",
  "קריית ים",
  "קריית מלאכי",
  "קריית שמונה",
  "צפת",
  "נתיבות",
  "אור יהודה",
  "גני תקווה",
  "כרמיאל",
  "יקנעם עילית",
  "מעלה אדומים",
  "אריאל",
  "דימונה",
  "מגדל העמק",
  "שדרות",
  "זכרון יעקב",
  "פרדס חנה-כרכור",
  "בית שאן",
  "אופקים",
  "גבעת שמואל",
];
